### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by pgierz** [pgierz/slurm-monitoring#2]
It would be great to see if the dependencies in the [`pyproject.toml`](./pyproject.toml) file are setup correctly.

At the moment, we have one section in `pyproject.toml` like so:

```toml
[tool.pixi.dependencies]
streamlit = ">=1.44.1,<2"
duckdb = ">=1.2.2,<2"
paramiko = ">=3.5.1,<4"
loguru = ">=0.7.2,<0.8"
click = ">=8.1.8,<9"
requests = ">=2.32.3,<3"
```

I'm not sure if these instead belong into the `[project.dependencies]` section instead.
